const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');

const envLocal = fs.readFileSync('.env.local', 'utf8');
const env = envLocal.split('\n').reduce((acc, line) => {
  const [key, value] = line.split('=');
  if (key && value) acc[key.trim()] = value.trim();
  return acc;
}, {});

const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

async function run() {
  const { data, error } = await supabase.rpc('exec_sql', {
    sql_string: `
      CREATE TABLE IF NOT EXISTS announcements (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        content TEXT NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
      ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS "Enable read access for all users" ON announcements;
      DROP POLICY IF EXISTS "Enable insert for all users" ON announcements;
      CREATE POLICY "Enable read access for all users" ON announcements FOR SELECT USING (true);
      CREATE POLICY "Enable insert for all users" ON announcements FOR INSERT WITH CHECK (true);
    `
  });
  if (error) {
    console.error("RPC failed:");
    console.error(error);
  } else {
    console.log("Success:", data);
  }
}
run();
